app/controllers/api/v1/featured_scenarios_controller.rb, app/controllers/saved_scenario_users_controller.rb, app/models/featured_scenario.rb, config/routes.rb, spec/factories/saved_scenario.rb, spec/models/collection_spec.rb, spec/requests/api/featured_scenarios_spec.rb
Featured scenarios api and tests
=> Featured scenarios api and tests

app/views/identity/settings/index.html.erb, config/locales/identity.en.yml, config/locales/identity.nl.yml
Change email component and locales.
=> Added change email back in

app/controllers/featured_scenarios_controller.rb, app/controllers/saved_scenario_users_controller.rb, app/services/create_saved_scenario_user.rb, spec/factories/saved_scenario_user.rb, spec/factories/saved_scenario_users.rb, spec/services/create_saved_scenario_user_spec.rb
Ported scenario invite mailer logic to MyETM and updated the spec. Also updated the saved scenario user factory
=> Call scenario invite mailer from within MyETM

app/models/collection.rb, app/models/version.rb
Updating collections url generation and cleaning up filter method on collections.
=> Tidying collections

app/components/admin/featured_user_row/component.html.erb, app/components/admin/featured_user_row/component.rb, app/controllers/admin/featured_scenario_users_controller.rb, app/javascript/controllers/user_search_controller.js, app/models/featured_scenario_user.rb, app/views/admin/_block_right_menu.html.erb, app/views/admin/featured_scenario_users/edit.html.erb, app/views/admin/featured_scenario_users/index.html.erb, app/views/admin/featured_scenario_users/new.html.erb, config/locales/admin.en.yml, config/locales/admin.nl.yml, config/routes.rb
The form to create new featured users could be prettier but it does work 😄
=> Featured scenario user creation form

app/components/collections/row/component.html.erb, app/components/saved_scenarios/info/component.html.erb, app/components/saved_scenarios/row/component.html.erb, config/environments/development.rb, config/locales/en.yml, config/locales/nl.yml
Tested locales with   config.i18n.raise_on_missing_translations = true. I think now I've caught them all. I also turned off fallback locales for development so we might catch locales issues more easily in the future.
@kaskranenburgQ would you mind giving the Dutch a once over to make sure there's nothing too weird? I'd recommend just checking the first commit (0c92b6cfb79f21af64d93a06e7fd1c908ed9769c) because the second just re-orders everything.
=> Final locales

app/views/admin/staff_applications/_intro.html.haml, db/seeds.rb
Extended the description on how to configure local settings and added a seedfile for an admin user for users running locally for the first time.
=> Running locally

app/components/identity/newsletter_status_row_component.html.erb, app/controllers/identity/newsletter_controller.rb, app/views/identity/newsletter/update.turbo_stream.erb
I couldn't test the solution fully because the newsletters need to connect to their urls / audience lists for it to all work. I think the issue was mainly the turbo tags not matching so I hope by stringifying them it should be resolved?
=> Newsletters - no-content issue

app/controllers/identity/settings_controller.rb, app/jobs/identity/sync_user_job.rb, app/models/version.rb, app/services/update_private_scenarios.rb, lib/myetm/auth.rb, lib/myetm/staff_applications.rb, spec/myetm/auth_spec.rb
Updated auth methods for running locally, and sync user job to handle syncing other user parameters.
Also updated the local settings configs for staff applications.
=> Private Scenarios and local auth

app/mailers/scenario_invitation_mailer.rb, app/views/scenario_invitation_mailer/scenario_invitation.en.html.erb, app/views/scenario_invitation_mailer/scenario_invitation.nl.html.erb
Admittedly not fully tested because it's so laborious to set up email mocking for testing - but the link should be right at least!
Let's test it on beta before pushing to pro?
=> Collab email improvements

README.md
Thought I'd whip this up before Kyra starts testing tomorrow
=> Basic ReadME for MyETM

app/views/saved_scenarios/_block_right_sub_options.html.erb
Wrapped everything in a frame and disabled turbo on edit to prompt a refresh
=> Turbo issue with Edit

app/components/hovercard/component.html.erb, app/components/hovercard_with_version/component.html.erb, app/components/identity/token_component.html.erb, app/models/version.rb, app/views/collections/new.html.haml, app/views/collections/new_transition.html.erb, app/views/layouts/_block_right.html.haml, app/views/saved_scenario_history/index.html.erb, app/views/saved_scenario_users/index.html.erb, app/views/saved_scenarios/show.html.haml, app/views/static_pages/contact.html.haml, app/views/static_pages/terms.html.haml, config/locales/admin.nl.yml, config/locales/en.yml, config/locales/identity.en.yml, config/locales/identity.nl.yml, config/locales/nl.yml
This PR addresses fallout from Kyra's testing, primarily focusing on fixes for locales, links and minor layout issues.
=> Fixing testing fallout

app/controllers/application_controller.rb, app/controllers/collections_controller.rb, app/controllers/saved_scenarios_controller.rb, app/views/layouts/_welcome_back.html.erb, app/views/layouts/application.html.haml, config/locales/en.yml, config/locales/nl.yml
Anybody that has not logged in since Friday 21 feb 2025, will get a cute welcoming message that we are still the same!
=> Welcome to My Scenarios!

app/controllers/identity/newsletter_controller.rb
Replace turbo stream with component rather than partial.
=> Content missing newsletters

app/models/version.rb
...to account for nil url_prefix and ensure the urls build correctly.
=> Fixes for version model

app/views/static_pages/contact.html.haml
Quick fix for the form by enabling the timestamp
=> Added timestamp to invisible captcha

app/services/create_interpolated_collection.rb, spec/services/create_interpolated_collection_spec.rb
Stop double interpolating 2050 and don't include 2023 in interpolation.
=> Fix interpolation issues

config/environments/production.rb
Defining the asset_host explicitly in production should resolve password reset issue
=> Password reset fix

app/controllers/api/v1/saved_scenarios_controller.rb, app/models/saved_scenario.rb, app/models/saved_scenario_user.rb, spec/requests/api/saved_scenarios_spec.rb
Goes with: https://github.com/quintel/etmodel/pull/4427
=> Update show endpoint response.
